CREATE TABLE CARD (
    CARD_ID BIGINT PRIMARY KEY,
    CARD_TYPE TEXT,
    ALIAS TEXT,
    PAN TEXT,
    CVV TEXT,
    ACCOUNT_ID TEXT
);

CREATE TABLE ACCOUNT (
    ACCOUNT_ID BIGINT PRIMARY KEY,
    IBAN TEXT,
    BIC_SWIFT TEXT,
    CUSTOMER_ID BIGINT
);

CREATE TABLE CUSTOMER (
    CUSTOMER_ID BIGINT PRIMARY KEY,
    FIRST_NAME TEXT,
    LAST_NAME TEXT,
    OTHER_NAME TEXT,
    DATE_CREATED DATE
);